AWSTemplateFormatVersion: "2010-09-09"
Description: "ACM Certificate with DNS Validation for domain and www subdomain"

Parameters:
  DomainName:
    Type: String
    Description: "The domain name for the certificate (e.g., example.com)"
  HostedZoneId:
    Type: String
    Description: "The Route 53 Hosted Zone ID"
  TagValue:
    Type: String
    Description: "The tag value for the certificate"

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub "www.${DomainName}"
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
        - DomainName: !Sub "www.${DomainName}"
          HostedZoneId: !Ref HostedZoneId
      Tags:
        - Key: workload
          Value: !Ref TagValue

Outputs:
  CertificateArn:
    Description: "ARN of the created certificate"
    Value: !Ref Certificate
