AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template to create Route 53 public hosted zone"

Parameters:
  DomainName:
    Type: String
    Description: The domain name for the hosted zone (e.g., example.com)

Resources:
  PublicHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName
      HostedZoneConfig:
        Comment: !Sub "Public hosted zone for ${DomainName}"

Outputs:
  HostedZoneId:
    Description: "Hosted Zone ID"
    Value: !Ref PublicHostedZone

  NameServers:
    Description: "Nameservers for the hosted zone. Update these at your domain registrar."
    Value: !Join
      - ", "
      - !GetAtt PublicHostedZone.NameServers
