AWSTemplateFormatVersion: "2010-09-09"
Description: "Create DNS records for CloudFront distribution with existing S3 bucket as origin"

Resources:
  ApexAliasRecord:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Ref HostedZoneId # Your Route 53 hosted zone
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !Ref CloudFrontDomainName
        HostedZoneId: Z2FDTNDATAQYW2 # Fixed CloudFront hosted zone ID
        EvaluateTargetHealth: false

  WwwAliasRecord:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Sub "www.${DomainName}"
      Type: A
      AliasTarget:
        DNSName: !Ref CloudFrontDomainName
        HostedZoneId: Z2FDTNDATAQYW2 # Fixed CloudFront hosted zone ID
        EvaluateTargetHealth: false

Parameters:
  HostedZoneId:
    Type: String
    Description: "The ID of your Route 53 hosted zone"

  DomainName:
    Type: String
    Description: "The apex domain name (e.g., example.com)"

  CloudFrontDomainName:
    Type: String
    Description: "The CloudFront distribution domain name"
